version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-typescript-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8.4
    container_name: express-typescript-mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME:-express_auth_db}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASS:-}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
    driver: bridge
