version: "3.8"

services:
  db:
    image: mysql:8.4
    container_name: express-typescript-mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME:-test_be_vehicle_tracker_db}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-root}
      # Jangan set MYSQL_USER jika ingin pakai user root!
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-typescript-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - .:/app:ro
      - /app/node_modules

volumes:
  db-data:

networks:
  backend:
    driver: bridge
